name: Update Rootelo DEV Mirror (Future)

on:
  push:
    branches:
      - future
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build RDL League
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python main.py --league rdl
          mkdir -p build_site
          cp *.html build_site/
          cp -r static build_site/
          cp -r assets build_site/
          cp -r api build_site/

      - name: Build HOOT League
        env:
          ROOTDB_TOKEN: ${{ secrets.ROOTDB_TOKEN }}
        run: |
          python main.py --league hoot
          cp -r hoot build_site/
          cp -r api build_site/

      - name: Deploy to rootelo-dev repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEV_REPO_PAT }}
          external_repository: tricholome/rootelo-dev
          publish_dir: ./build_site
          publish_branch: gh-pages
